services:
  backend:
    build: .
    container_name: backend_django
    ports:
      - "${APP_PORT}:8080"
    environment:
      - PIPELINE=production
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks:
      - app-network
    env_file: .env

  db:
    image: postgres:latest
    container_name: db_postgresql
    ports:
      - "${POSTGRES_OUT_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file: .env

  redis:
    image: redis:latest
    container_name: ws-redis
    ports:
      - "${REDIS_OUT_PORT}:6379"
    volumes:
      - redis-data:/data
    command: redis-server
    restart: always
    networks:
      - app-network
    env_file: .env

volumes:
  postgres_data:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge